variable "namespace" {
  description = "Kubernetes namespace to deploy Prometheus into"
  type        = string
  default     = "monitoring"
}

variable "create_namespace" {
  description = "Whether to create the namespace"
  type        = bool
  default     = true
}

variable "helm_chart_version" {
  description = "Version of the kube-prometheus-stack Helm chart"
  type        = string
  default     = "67.4.0" # Latest stable as of Dec 2024
}

# Prometheus Configuration
variable "retention_days" {
  description = "Number of days to retain metrics"
  type        = string
  default     = "15d"
}

variable "storage_class" {
  description = "Storage class for Prometheus persistence (e.g., standard for Kind, gp3 for EKS)"
  type        = string
  default     = "standard"
}

variable "prometheus_volume_size" {
  description = "Size of the Prometheus persistent volume"
  type        = string
  default     = "10Gi"
}

variable "service_type" {
  description = "Kubernetes Service type for Prometheus (ClusterIP, NodePort, LoadBalancer)"
  type        = string
  default     = "ClusterIP"
  validation {
    condition     = contains(["ClusterIP", "NodePort", "LoadBalancer"], var.service_type)
    error_message = "Service type must be one of: ClusterIP, NodePort, or LoadBalancer."
  }
}

# Grafana Configuration
variable "grafana_enabled" {
  description = "Enable Grafana deployment"
  type        = bool
  default     = true
}

variable "grafana_admin_password" {
  description = "Admin password for Grafana. If null, it will be auto-generated by the chart."
  type        = string
  default     = null
  sensitive   = true
}

variable "grafana_volume_size" {
  description = "Size of the Grafana persistent volume"
  type        = string
  default     = "5Gi"
}

# Alertmanager Configuration
variable "alertmanager_enabled" {
  description = "Enable Alertmanager deployment"
  type        = bool
  default     = true
}

variable "alertmanager_volume_size" {
  description = "Size of the Alertmanager persistent volume"
  type        = string
  default     = "2Gi"
}

# Ingress Configuration
variable "prometheus_ingress_enabled" {
  description = "Enable Ingress for Prometheus"
  type        = bool
  default     = false
}

variable "prometheus_ingress_host" {
  description = "Hostname for Prometheus Ingress"
  type        = string
  default     = "prometheus.local"
}

variable "grafana_ingress_enabled" {
  description = "Enable Ingress for Grafana"
  type        = bool
  default     = false
}

variable "grafana_ingress_host" {
  description = "Hostname for Grafana Ingress"
  type        = string
  default     = "grafana.local"
}

variable "ingress_class_name" {
  description = "Ingress class name (e.g., nginx, alb)"
  type        = string
  default     = "nginx"
}

# Extensibility
variable "additional_set_values" {
  description = "Additional key-value pairs to pass to the Helm chart"
  type = list(object({
    name  = string
    value = string
  }))
  default = []
}
