variable "namespace" {
  description = "Kubernetes namespace to deploy Jenkins into"
  type        = string
  default     = "jenkins"
}

variable "create_namespace" {
  description = "Whether to create the namespace"
  type        = bool
  default     = true
}

variable "helm_chart_version" {
  description = "Version of the Jenkins Helm chart"
  type        = string
  default     = "5.1.5" # Pin to specific version for stability
}

variable "admin_password" {
  description = "Admin password for Jenkins. If empty, it will be auto-generated by the chart."
  type        = string
  default     = null
  sensitive   = true
}

variable "storage_class" {
  description = "Storage class for Jenkins persistence (e.g., standard for Kind, gp3 for EKS)"
  type        = string
  default     = "standard"
}

variable "volume_size" {
  description = "Size of the persistent volume"
  type        = string
  default     = "8Gi"
}

variable "ingress_enabled" {
  description = "Enable Ingress generation"
  type        = bool
  default     = false
}

variable "ingress_host" {
  description = "Hostname for the Ingress"
  type        = string
  default     = "jenkins.local"
}

variable "ingress_class_name" {
  description = "Ingress class name (e.g., nginx, alb)"
  type        = string
  default     = "nginx"
}

variable "jenkins_url_protocol" {
  description = "Protocol for Jenkins URL (http or https)"
  type        = string
  default     = "http"
  validation {
    condition     = contains(["http", "https"], var.jenkins_url_protocol)
    error_message = "Protocol must be either 'http' or 'https'."
  }
}

variable "service_type" {
  description = "Kubernetes Service type (ClusterIP, NodePort, LoadBalancer)"
  type        = string
  default     = "ClusterIP"
  validation {
    condition     = contains(["ClusterIP", "NodePort", "LoadBalancer", "ExternalName"], var.service_type)
    error_message = "Service type must be one of: ClusterIP, NodePort, LoadBalancer, or ExternalName."
  }
}

variable "additional_set_values" {
  description = "Additional key-value pairs to pass to the Helm chart"
  type = list(object({
    name  = string
    value = string
  }))
  default = []
}
